### ISSUE TITLE
External Templates Failing

### ISSUE THREAD

**Issue by sosensible** [portainer/templates#104]
I used the following docker-compose file to get custom templates working, but it could not see them.

```
version: '3.6'

services:
  proxy:
    build: nginx/
    container_name: "devops-proxy"
    ports:
      - "80:80"
    networks:
      - local

  templates:
    image: portainer/templates
    container_name: "devops-portainer-templates"
    networks:
      - local
    volumes:
      - type: bind
        source: ~/dev/source/devops/templates/templates.json
        target: /usr/share/nginx/html/templates.json

  portainer:
    image: portainer/portainer
    restart: always
    container_name: "devops-portainer"
#Automatically choose 'Manage the Docker instance where Portainer is running' by adding <--host=unix:///var/run/docker.sock> to the command
    command: --templates http://templates/templates.json
    networks:
      - local
    ports:
      - "9999:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: bind
        source: ~/Volumes/portainer
        target: /data

  watchtower:
    image: v2tec/watchtower
    container_name: "devops-watchtower"
    command: --cleanup portainer-app portainer-watchtower portainer/templates
    networks:
      - local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  local:
    driver: bridge

```
