### ISSUE TITLE
Nginx proxy manager template

### ISSUE THREAD

**Issue by danielgroen** [portainer/templates#167]
Just like the traefik template, [Nginx proxy manager](https://nginxproxymanager.com/) would also be a good enhancement

```
version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
```
